spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    time-zone: Asia/Ho_Chi_Minh
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: clovernetworkvn@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: spjxgkfcikcajsrc
  datasource:
    username: clover
    password: lambmt0910
    url: jdbc:postgresql://clover-network-database.ck32a9mfyksb.ap-southeast-1.rds.amazonaws.com/db_clover_network
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: clover
clover:
  server_host: https://clover-app-pju97.ondigitalocean.app
  local_host: localhost:8080
  fe_url: https://clover-network.vercel.app
app_setting:
  firebase:
    bucket_name: 'clover-network-afd47.appspot.com'

