spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ytbbuilamsonla@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ohrxnidvjxdjvjwx
  datasource:
    password: d524478cbc54b568d3ea983321d9ce80d54dae6de5ffc44857b5225de090f244
    username: ajiegpzngvuzvn
    initialization-mode: always
    url: jdbc:postgresql://ec2-54-156-8-21.compute-1.amazonaws.com/d6clis65tpgv4q
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: clover
clover:
  server_host: https://clover-network-service-fd0c2a440af1.herokuapp.com
  local_host: localhost:8080

