server:
  ssl:
    key-store: classpath:springboot.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: springboot
    key-password: password
  port: 8080
spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ytbbuilamsonla@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ohrxnidvjxdjvjwx
  datasource:
    password: postgres
    username: postgres
    initialization-mode: always
    url: jdbc:postgresql://clover-db.ck32a9mfyksb.ap-southeast-1.rds.amazonaws.com/clover_db
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: clover
clover:
  server_host: 47.128.64.91:8080
  local_host: localhost:8080

