spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ytbbuilamsonla@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ohrxnidvjxdjvjwx
  datasource:
    password: 3vFokhxJZIK2
    username: lambmt.work
    initialization-mode: always
    schema: classpath:/sql-script/schema.sql
    url: jdbc:postgresql://ep-white-limit-63473907.ap-southeast-1.aws.neon.tech/clover_network
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: abc
clover:
  server_host: https://clover-network-service.onrender.com
  local_host: localhost:8080

