spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ytbbuilamsonla@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ohrxnidvjxdjvjwx
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://db-clovernetwork.ck32a9mfyksb.ap-southeast-1.rds.amazonaws.com/db_clover_network
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: clover
clover:
  server_host: https://clover-network-service-fd0c2a440af1.herokuapp.com
  local_host: localhost:8080

