server:
  port: 8080
spring:
  profiles:
    active: local
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: 'true'
  mail:
    host: smtp.gmail.com
    username: ytbbuilamsonla@gmail.com
    port: '587'
    properties:
      mail:
        smtp:
          starttls:
            enable: 'true'
          auth: 'true'
    password: ohrxnidvjxdjvjwx
  datasource:
    password: postgres
    username: postgres
    initialization-mode: always
    schema: classpath:/sql-script/schema.sql
    url: jdbc:postgresql://localhost:5432/CloverDB
    continue-on-error: 'true'
    initialize: 'true'
redis:
  port: '6379'
  host: localhost
jwt:
  secret: abc
clover:
  server_host: localhost:8080
  local_host: localhost:8080
  
