name: Deploy Clover Network Service to EC2

on:
  push:
    branches:
      - main
      
env:
  JAR_FILE_NAME: 'clover_network-0.0.1-SNAPSHOT.jar'
  EC2_HOST: ${{ secrets.EC2_HOST }}
  EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
  EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Build JAR
      run:  mvn package -DskipTests
    
    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_PRIVATE_KEY }}
        source: 'target/${{ env.JAR_FILE_NAME }}'
        target: 'clover_network_service'
        
    - name: Deploying ... 
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_HOST }}
        username: ${{ env.EC2_USERNAME }}
        key: ${{ env.EC2_PRIVATE_KEY }}
        script: |
          {
            if tmux ls | awk -F: '{print $1}' | grep -wq "deployment"; then
              tmux kill-session -t deployment
            fi
          }
          cd clover_network_service/target
          tmux new-session -d -s deployment 'java -jar ${{ env.JAR_FILE_NAME }}'
